version: '3.1'

services:

# ReverseProxy ------------------------------------------------------

  envoy:
    build: ./EnvoyProxy/
    restart: always   
    networks:
       - incloudnetwork
  
# Databases ------------------------------------------------------

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-16.04
    restart: always   
    networks:
        - incloudnetwork
 
  redis:
    build: ./Redis/
    restart: always   

# identity ------------------------------------------------------

  identity-api:
    build: ./Services/Identity/Identity.API
    restart: always
    depends_on:
        - mssqlserver
    networks:
        - incloudnetwork

# Services ------------------------------------------------------

  std-gateway:
    build: ./ApiGateways/Standart/StandartGateway/
    restart: always
    networks:
      - incloudnetwork
    depends_on:
        - envoy    
    networks:
        - incloudnetwork

  volumes-api:
    build:
      context: ./Services/
      dockerfile: Dockerfile.volumes
    restart: always
    depends_on:
        - redis    
    networks:
        - incloudnetwork

  instances-api:
    build:
      context: ./Services/
      dockerfile: Dockerfile.instances
    restart: always
    depends_on:
        - mssqlserver   
    networks:
        - incloudnetwork

networks:
   incloudnetwork:
       driver: bridge
