version: '3.1'

services:

# Proxy ------------------------------------------------------

  envoy:
    build: ./EnvoyProxy/
    restart: always
    ports:
      - 8705:80
      - 8706:8001
    networks:
       - incloudnetwork
  
# Databases ------------------------------------------------------

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-16.04
    restart: always
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: "InCloudP@66w0rd2z"
    ports:
        - 8711:1433
    volumes:
        - /opt/incloud/db/mssqlserver/data:/var/opt/mssql/data
        - /opt/incloud/db/mssqlserver/log:/var/opt/mssql/log
        - /opt/incloud/db/mssqlserver/secrets:/var/opt/mssql/secrets
    networks:
        - incloudnetwork
 
  redis:
    build: ./Redis/
    restart: always
    volumes:
      - /opt/incloud/db/redis/data:/data
    ports:
      - 8712:6379


# Services ------------------------------------------------------

  std-gateway:
    build: ./ApiGateways/Standart/StandartGateway/
    restart: always
    networks:
      - incloudnetwork
    depends_on:
        - envoy
    links:
        - envoy:envoy
    environment:
        - "ASPNETCORE_URLS=http://*:5000;https://*:5001"
        - "ASPNETCORE_urls__identity=envoy/identity"
        - "ASPNETCORE_urls__volumes=envoy/volumes"
        - "ASPNETCORE_urls__instances=envoy/instances"
    ports:
        - 8717:5000
        - 8718:5001
    networks:
        - incloudnetwork

  identity-api:
    build: ./Services/Identity/Identity.API
    restart: always
    depends_on:
        - mssqlserver
    links:
        - mssqlserver:mssqlserver
    environment:
        - ASPNETCORE_URLS=http://*:5000;https://*:5001
        - ASPNETCORE_ConnectionStrings__IdentityDbContext=Server=mssqlserver;Database=incloudidentityservice;User id=sa;Password=InCloudP@66w0rd2z;Trusted_Connection=True;MultipleActiveResultSets=true;Integrated Security=false
    ports:
        - 8713:5000
        - 8714:5001
    networks:
        - incloudnetwork

  volumes-api:
    build:
      context: ./Services/
      dockerfile: Dockerfile.volumes
    restart: always
    depends_on:
        - redis
    links:
        - redis:redis
    environment:
        - ASPNETCORE_URLS=http://*:5000;https://*:5001
    ports:
        - 8715:5000
        - 8716:5001
    networks:
        - incloudnetwork

  

networks:
   incloudnetwork:
       driver: bridge
